feat: enum support
fabien0102/openapi-codegen pull request #153
Opened 2023-04-11 18:04 UTC by alan-oliv

# Description

This is a new feature that enables outputting enums instead of string unions, even without open-api enum $ref in generated swagger schema. (Fixes #133)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How to
in your defineConfig, you have to pass `useEnums: true`

![image](https://user-images.githubusercontent.com/4368481/231252540-7a5340c9-b4ac-47ad-ac6a-e9cd49fd41e8.png)

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Support
- [x] String enums
- [x] Integer enums
- [x] Boolean enums

## String enums
Given a schema:
`
  "MyStringEnum": {
      "type": "string",
       "enum": ["ENABLED", "DISABLED"]
   }
`

the output will be:
`
export enum MyStringEnum {
  ENABLED = "ENABLED",
  DISABLED = "DISABLED",
}`

## Int enums
Given a schema:
`
  "MyIntEnum": {
        "type": "int",
        "enum": [0, 1, 2, 3, 4]
    }
`

the output will be:
`
export enum MyIntEnum {
  ZERO = 0,
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
}`

## Boolean enums
Given a schema:
`
  "MyBooleanEnum": {
        "type": "boolean",
        "enum": [true, false]
    }
`

the output will be:
`
export enum MyBooleanEnum {
  True,
  False
}`

2023-04-11 18:05 UTC, shadowlik commented
+1 to this feature

2023-04-11 18:14 UTC, davidsonsns commented
+1

2023-04-11 18:43 UTC, DavidVeloso commented
+1

2023-04-12 07:21 UTC, fabien0102 requested changes
Amazy pull-request! Thanks a lot for this contribution, let’s just add a little unit test on `convertNumberToWord` and we are good to go!

2023-04-12 07:21 UTC, fabien0102 commented on plugins/typescript/src/utils/getEnumProperties.ts
> +export const convertNumberToWord = (n: number): string => {
Let’s add a dummy unit-test for this util, like a little loop to test, let’s say, the main/tricky cases 😉

2023-04-12 12:19 UTC, fabien0102 approved these changes
Amazing!

2023-04-12 13:04 UTC, merged